# Generated by Django 4.0.4 on 2022-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='picture',
            field=models.ImageField(upload_to='tours/'),
        ),
    ]
